// <auto-generated />
namespace Amex.CCA.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datatypereset2force : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datatypereset2force));
        
        string IMigrationMetadata.Id
        {
            get { return "201709010857025_datatypereset2-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
