// <auto-generated />
namespace Amex.CCA.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datatyperesetmax : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datatyperesetmax));
        
        string IMigrationMetadata.Id
        {
            get { return "201709010904141_datatyperesetmax"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
